return {
  lua = { "lua_ls" },
  html = { "html" },
  css = { "cssls" },
  typescript = { "ts_ls" },
  -- "harper_ls",
  ["yaml.docker-compose"] = { "docker_compose_language_service" },
  ["docker-langserver"] = { "dockerls" },
  c = { "clangd" },
  cpp = { "clangd" },
  objc = { "clangd" },
  objcpp = { "clangd" },
  cuda = { "clangd" },
  bash = { "bashls" },
  sh = { "bashls" },
  python = { "ruff" },
  -- {"basedpyright"},
  go = { "gopls", "golangci_lint_ls" },
  gomod = { "gopls", "golangci_lint_ls" },
  gowork = { "gopls" },
  gotmpl = { "gopls" },
  nginx = { "nginx_language_server" },
  scss = { "somesass_ls" },
  sass = { "somesass_ls" },
  json = { "jsonls" },
  jsonc = { "jsonls" },
  java = { "java_language_server" },
}
